### ISSUE TITLE
Dockerhub TAG versions ?

### ISSUE THREAD

**Issue by zaggash** [EugenMayer/docker-image-portus#15]
Hi, I saw you pushed 2 version since 2.4-rc11 

Don't you add portus version tag on new build ?
Or it is just build from master ?

**Comment by EugenMayer** [comment]
Not sure what you refer but i guess its about hub.docker... yes the pushes to master build to "latest", but yet i did not tag a version. One of the reasons is that i yet did not adjust the rancher catalog since id not find enough time, i would like to sync the new tag with a release there.

does it pressure you to have such a tag?

**Comment by zaggash** [comment]
Yep, I'm talking about dockerhub :) 
Nop its ok, but I do not create a container with an image tag to latest so I wont use the latest updated image. 
Its not a big deal at the moment. 
I wanted to be sure you will add tag later on related to Portus version.  

Regards

**Comment by EugenMayer** [comment]
Yes, the image versions are not aligned yet because portus had one version for 6 months while i was building from source. I will go back to synced versions as soon as they stablelize on this matter.
